name: Deploy app - Production

on:
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        tags: true


    - name: Show file changes between releases
      run: |
        current_tag="${{ github.event.release.tag_name }}"
        previous_tag=$(git tag --sort=creatordate | tail -n 2 | head -n 1)
        echo "Current tag: $current_tag"
        echo "Previous tag: $previous_tag"
        echo "Files changed between $previous_tag and $current_tag:"
        git diff --name-only $previous_tag $current_tag > changed_files.txt
        cat changed_files.txt
        echo "apps/category-page-app/" >> changed_files.txt
        if grep -qE '^(apps/category-page-app/|turbo.json|yarn.lock|postcss.config.js|github/workflows/prod_deploy_category_page.yaml|packages/|deployments/charts/category-page-mfe/values_prod.yaml|deployments/configs_prod.*\.properties|deployments/conf.nginx)' changed_files.txt; then
           echo "category_changed=true"
        else
           echo "category_changed=false"
        fi. 
    - name: Deploy Category Page
      if: steps.changed.outputs.category_changed == 'true'
      run: |
        echo "Category page deploy triggered"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "21"

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Install AWS CLI v2
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
