name: Deploy app - Production

on:
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Show release and source branch info
      run: |
        echo "Release Tag: ${{ github.event.release.tag_name }}"
        echo "Source Branch: ${{ github.event.release.target_commitish }}"

    - name: Fetch source branch
      run: |
        git fetch origin ${{ github.event.release.target_commitish }}

    - name: Compare release to source branch tip
      id: diff
      run: |
        echo "Changed files:"
        git diff --name-only origin/${{ github.event.release.target_commitish }} ${{ github.event.release.tag_name }} > changed_files.txt
        cat changed_files.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "21"

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Install AWS CLI v2
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
