name: Deploy app - Production

on:
  release:
    types:
      - created

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Determine previous tag
      id: get_tags
      run: |
        current_tag="${{ github.event.release.tag_name }}"
        all_tags=($(git tag --sort=creatordate))
        previous_tag=""
        echo $all_tags

        for i in "${!all_tags[@]}"; do
          if [[ "${all_tags[$i]}" == "$current_tag" ]] && (( i > 0 )); then
            previous_tag="${all_tags[$((i-1))]}"
            break
          fi
        done

        echo "Current tag: $current_tag"
        echo "Previous tag: $previous_tag"

        echo "previous_tag=$previous_tag" >> $GITHUB_OUTPUT

    - name: Show file changes between releases
      run: |
        echo "Files changed between ${{ steps.tags.outputs.previous_tag }} and ${{ github.event.release.tag_name }}:"
        git diff --name-only ${{ steps.get_tags.outputs.previous_tag }} ${{ github.event.release.tag_name }} > changed_files.txt
        cat changed_files.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "21"

    - name: Install Helm
      run: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Install AWS CLI v2
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
